=== alftacmir/LM_21_22/U1/U1_T3_Validating_with_schema/ej1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Miembros">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Miembro" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Nombre"/>
              <xs:element type="xs:positiveInteger" name="Tiempo_membresia"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== alftacmir/LM_21_22/U1/U1_T3_Validating_with_schema/ej1.xml
<?xml version="1.0" encoding="utf-8"?>
<Miembros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ej1.xsd">
    <Miembro>
        <Nombre>Chris Smith</Nombre>
        <Tiempo_membresia>4</Tiempo_membresia>
    </Miembro>
    <Miembro>
        <Nombre>Judi Zimmerman</Nombre>
        <Tiempo_membresia>5</Tiempo_membresia>
    </Miembro>
    <Miembro>
        <Nombre>Michael Calder</Nombre>
        <Tiempo_membresia>3</Tiempo_membresia>
    </Miembro>
</Miembros>
